export const products = [
  {
    id: 1,
    image: 'moisturizing_mousse',
    skinType: 'normal skin',
    title: 'Moisturizing mousse',
    description: 'Deeply hydrates facial skin, leaving it soft and smooth.',
    composition: [
      'active natural complexes',
      'vitamins C, A, PP, B and E',
      'sun protection components',
    ],
    price: 2750,
    currency: '₽',
  },
  {
    id: 2,
    image: 'moisturizing_mask',
    skinType: 'normal skin',
    title: 'Moisturizing mask',
    description: 'Helps retain moisture in the upper layers of the skin.',
    composition: ['waxes', 'minerals', 'oils'],
    price: 3500,
    currency: '₽',
  },
  {
    id: 3,
    image: 'cleansing_gel',
    skinType: 'normal skin',
    title: 'Cleansing gel',
    description:
      'Cleanses intensely without damaging the skin’s protective barrier.',
    composition: [
      'minerals',
      'vitamins C, A, PP, B and E',
      'sun protection components',
    ],
    price: 1650,
    currency: '₽',
  },
  {
    id: 4,
    image: 'gift_set_number_one',
    skinType: 'normal skin',
    title: 'Gift set No. 1',
    description: 'A set consisting of a moisturizing cream and a mask.',
    composition: ['waxes', 'minerals', 'oils'],
    price: 4750,
    currency: '₽',
  },
  {
    id: 5,
    image: 'gift_set_number_five',
    skinType: 'normal skin',
    title: 'Gift set No. 5',
    description:
      'The full Invisible Symphony set: cream, mask, mousse, and cleansing gel.',
    composition: ['waxes', 'minerals', 'oils'],
    price: 7520,
    currency: '₽',
  },
];